<?php

/**
 * Implementation of hook_install().
 */
function nocase_install() {
  $t = get_t();
  drupal_set_message($t('Nocase module: Installation script complete. It is important that you read through README.txt to familiarise yourself with some of the caveats of this module.'));
}

/**
 * Implementation of hook_uninstall().
 */
function nocase_uninstall() {
  $t = get_t();
  drupal_set_message($t('Nocase module: Uninstallation script complete.'));
}
